name: microsleep_mobile
description: "Microsleep Guard â€” Sistem deteksi microsleep berbasis IoT dan Deep Learning."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # ğŸ“± UI & Icon
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  curved_navigation_bar: ^1.0.3

  # ğŸŒ Maps & Lokasi
  google_maps_flutter: ^2.12.3
  geolocator: ^13.0.1

  # ğŸ”” Notifikasi & Permission
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.0

  # â˜ï¸ Firebase
  firebase_core: ^3.5.0
  firebase_database: ^11.0.0

  # ğŸ“Š Date & Format
  intl: ^0.19.0

  # ğŸ”Š Audio Player
  audioplayers: ^6.0.0

  # ğŸï¸ Animasi (Lottie JSON)
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ğŸ§© Daftar asset lokal
  assets:
    - assets/monyet.jpeg
    - assets/gambar.png
    - assets/animation/Red Car Drive.json
    - assets/animation/sign in red.json
    - assets/animation/red 1.json
    - assets/animation/Black Check.json
    - assets/sound/alarm.wav
