name: microsleep_mobile
description: "Microsleep Guard â€” Sistem deteksi microsleep berbasis IoT dan Deep Learning."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  curved_navigation_bar: ^1.0.3
  shared_preferences: ^2.2.2
  provider: ^6.1.2

  google_maps_flutter: ^2.12.3
  geolocator: ^13.0.1

  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.0

  firebase_core: ^3.5.0
  firebase_database: ^11.0.4

  # Background Service versi stabil
  flutter_background_service: ^5.0.7
  flutter_background_service_android: ^6.1.0

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  audioplayers: ^6.0.0
  vibration: ^1.7.4
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.3

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated

flutter:
  uses-material-design: true

  assets:
    - assets/monyet.jpeg
    - assets/gambar.png
    - assets/animation/Red Car Drive.json
    - assets/animation/sign in red.json
    - assets/animation/red 1.json
    - assets/animation/Black Check.json
    - assets/flag_id.png
    - assets/flag_us.png
